### ISSUE TITLE
dies when querying a route with wrong parameters

### ISSUE THREAD

**Issue by dni** [Ride-The-Lightning/c-lightning-REST#105]
i connected to ride the lightning and tried to query a route in the graph lookup and put the node uri instead of the node pubkey, and the client died.

```
/home/btcnode/c-lightning-REST/node_modules/error/typed.js:31
        var result = new Error();
                     ^

Error [LightningError]: id: should be a node id: invalid token '"03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f@3.33.236.230:9735"'
    at createError (/home/btcnode/c-lightning-REST/node_modules/error/typed.js:31:22)
    at LightningClient.<anonymous> (/home/btcnode/c-lightning-REST/lightning-client-js.js:139:28)
    at Object.onceWrapper (node:events:646:26)
    at LightningClient.emit (node:events:526:28)
    at Parser.LightningClient.parser.onValue (/home/btcnode/c-lightning-REST/lightning-client-js.js:88:17)
    at Parser.proto.emit (/home/btcnode/c-lightning-REST/node_modules/jsonparse/jsonparse.js:337:8)
    at Parser.proto.pop (/home/btcnode/c-lightning-REST/node_modules/jsonparse/jsonparse.js:332:8)
    at Parser.proto.onToken (/home/btcnode/c-lightning-REST/node_modules/jsonparse/jsonparse.js:402:12)
    at Parser.proto.write (/home/btcnode/c-lightning-REST/node_modules/jsonparse/jsonparse.js:135:34)
    at LightningClient._handledata (/home/btcnode/c-lightning-REST/lightning-client-js.js:146:25) {
  type: 'lightning',
  code: -32602,
  fullType: 'lightning'
}
```

**Comment by saubyk** [comment]
Hi @dni thanks for reporting the issue.
Fix merged into the release branch. Will be available with release v0.7.1.
