### ISSUE TITLE
Cannot read properties of undefined (reading 'substring')

### ISSUE THREAD

**Issue by NicolasDorier** [Ride-The-Lightning/c-lightning-REST#187]
We are having this error, making RTL not working on v23.05

saubyk/c-lightning-rest:0.10.4
btcpayserver/lightning:v23.05

```
warn: --- Starting the cl-rest server ---
warn: --- cl-rest api server is ready and listening on 0.0.0.0:3001 ---
warn: --- cl-rest doc server is ready and listening on 0.0.0.0:4001 ---
warn: Client disconnected, total clients: 0
TypeError: Cannot read properties of undefined (reading 'substring')
    at isVersionCompatible (/usr/src/app/utils/utils.js:4:51)
    at exports.getFees (/usr/src/app/controllers/getFees.js:32:49)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:144:13)
    at module.exports (/usr/src/app/utils/tasteMacaroon.js:18:5)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:15
warn: {}
warn: {}
```

**Comment by ShahanaFarooqui** [comment]
Closing with PR #188.

**Comment by NicolasDorier** [comment]
thanks a lot, tested it works.
