### ISSUE TITLE
Tests fail on core-lightning 22.11.1

### ISSUE THREAD

**Issue by ErikDeSmedt** [Ride-The-Lightning/c-lightning-REST#192]
I'm running lightning version 22.11.1.

When I run `npm test` I get the following error

```
  1) lnnode
       /GET getinfo
         it should return getinfo from the node:
     Uncaught AssertionError: expected { …(17) } to have property 'msatoshi_fees_collected'
      at /home/erik/code/c-lightning-REST/test/mainTest.js:62:41
      at Request.callback (node_modules/superagent/lib/node/index.js:716:12)
      at /home/erik/code/c-lightning-REST/node_modules/superagent/lib/node/index.js:916:18
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/parsers/json.js:19:7)
      at IncomingMessage.emit (node:events:524:35)
      at endReadableNT (node:internal/streams/readable:1378:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by ShahanaFarooqui** [comment]
@ErikDeSmedt Thank you for raising the issue. It has been fixed and will be released with v0.10.6
