### ISSUE TITLE
certs directory can't be created

### ISSUE THREAD

**Issue by cotsuka** [Ride-The-Lightning/c-lightning-REST#193]
Attempting to run c-lightning-REST as a `lightningd` plugin. I think the issue is likely due to not using the default folder setup and the hard-coded paths starting with `./` aren't creating the folder in an expected location.

### Error
```
Jul 06 07:27:28 tanto systemd[1]: Starting Core Lightning daemon...
Jul 06 07:27:33 tanto lightningd[189346]: ..+......+.........+......+.+.........+........+...+.........+.+...............+...+...............+..+++++++++>
Jul 06 07:27:33 tanto lightningd[189346]: ...+++++++++++++++++++++++++++++++++++++++*........+.....+.+++++++++++++++++++++++++++++++++++++++*.+.......+..>
Jul 06 07:27:33 tanto lightningd[189346]: req: Can't open "./certs/key.tmp.pem" for writing, No such file or directory
Jul 06 07:27:33 tanto lightningd[189346]: node:fs:592
Jul 06 07:27:33 tanto lightningd[189346]:   handleErrorFromBinding(ctx);
Jul 06 07:27:33 tanto lightningd[189346]:   ^
Jul 06 07:27:33 tanto lightningd[189346]: Error: ENOENT: no such file or directory, open './certs/key.pem'
Jul 06 07:27:33 tanto lightningd[189346]:     at Object.openSync (node:fs:592:3)
Jul 06 07:27:33 tanto lightningd[189346]:     at Object.readFileSync (node:fs:460:35)
Jul 06 07:27:33 tanto lightningd[189346]:     at Object.<anonymous> (/usr/lib/node_modules/c-lightning-rest/cl-rest.js:79:13)
Jul 06 07:27:33 tanto lightningd[189346]:     at Module._compile (node:internal/modules/cjs/loader:1257:14)
Jul 06 07:27:33 tanto lightningd[189346]:     at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
Jul 06 07:27:33 tanto lightningd[189346]:     at Module.load (node:internal/modules/cjs/loader:1115:32)
Jul 06 07:27:33 tanto lightningd[189346]:     at Module._load (node:internal/modules/cjs/loader:962:12)
Jul 06 07:27:33 tanto lightningd[189346]:     at Module.require (node:internal/modules/cjs/loader:1139:19)
Jul 06 07:27:33 tanto lightningd[189346]:     at require (node:internal/modules/helpers:121:18)
Jul 06 07:27:33 tanto lightningd[189346]:     at restPlugin.onInit (/usr/lib/node_modules/c-lightning-rest/clrest.js:32:12) {
Jul 06 07:27:33 tanto lightningd[189346]:   errno: -2,
Jul 06 07:27:33 tanto lightningd[189346]:   syscall: 'open',
Jul 06 07:27:33 tanto lightningd[189346]:   code: 'ENOENT',
Jul 06 07:27:33 tanto lightningd[189346]:   path: './certs/key.pem'
Jul 06 07:27:33 tanto lightningd[189346]: }
Jul 06 07:27:33 tanto lightningd[189346]: Node.js v20.3.1
```

### `lightningd` Config
```
# Bitcoin Control Options
network=bitcoin
bitcoin-datadir=/mnt/nvme/bitcoin
bitcoin-rpcuser=REMOVED
bitcoin-rpcpassword=REMOVED
bitcoin-rpcconnect=127.0.0.1
bitcoin-rpcport=8332

# Lightning Daemon Options
lightning-dir=/mnt/nvme/lightning
log-file=/mnt/nvme/lightning/debug.log
wallet=postgres://REMOVED

# Lightning Node Customization Options
alias=REMOVED
rgb=FFA500
fee-base=0

# Lightning Channel and HTLC Options
large-channels
funding-confirms=10

# Networking Options
bind-addr=127.0.0.1:9735
addr=statictor:127.0.0.1:9051
proxy=127.0.0.1:9050
always-use-proxy=true

# Lightning Plugins
## load plugins from a directory
plugin-dir=/mnt/nvme/lightning/plugins

## c-lightning-rest
plugin=/usr/lib/node_modules/c-lightning-rest/clrest.js
rest-port=3002
rest-docport=4001
rest-protocol=http
rest-lnrpcpath=/mnt/nvme/lightning/bitcoin/lightning-rpc

# Experimental Options
experimental-onion-messages
experimental-offers
experimental-dual-fund
```

### systemd Service
```
[Unit]
Description=Core Lightning daemon
Requires=bitcoind.service
After=bitcoind.service
Wants=network-online.target
After=network-online.target

[Service]
ExecStart=/usr/bin/lightningd --daemon --conf /etc/lightningd/lightningd.conf --pid-file=/run/lightningd/lightningd.pid

# Creates /run/lightningd owned by bitcoin
RuntimeDirectory=lightningd
# Creates /etc/lightningd owned by bitcoin
ConfigurationDirectory=lightningd

User=bitcoin
Group=bitcoin
Type=forking
PIDFile=/run/lightningd/lightningd.pid
Restart=on-failure

# Hardening measures
####################

# Provide a private /tmp and /var/tmp.
PrivateTmp=true

# Mount /usr, /boot/ and /etc read-only for the process.
ProtectSystem=full

# Disallow the process and all of its children to gain
# new privileges through execve().
NoNewPrivileges=true

# Use a new /dev namespace only populated with API pseudo devices
# such as /dev/null, /dev/zero and /dev/random.
PrivateDevices=true

# Deny the creation of writable and executable memory mappings.
# NOTE: This seems to break node.js plugins, notably Ride-The-Lightning/c-lightning-REST:
#  https://github.com/Ride-The-Lightning/c-lightning-REST/issues/116
MemoryDenyWriteExecute=false

[Install]
WantedBy=multi-user.target
```

**Comment by cotsuka** [comment]
@saubyk Still seeing the same error on 0.10.5.

**Comment by ShahanaFarooqui** [comment]
@cotsuka It is generally not a good practice to directly install any application into /usr/lib/node_modules or any global system directory. User generally require admin rights (root) to make modifications to this directory and running installations as root can pose a security risk.

That being said, if you still want to keep it at the same location, you have to run the application as root or create ./certs folder manually with necessary permissions.

**Comment by cotsuka** [comment]
@ShahanaFarooqui I understand now it's trying to create `certs` in the `node_modules/c-lightning-rest` folder. I'll make some changes on my end to move where the module is installed. This seems to be a difference between [Arch's PKGBUILD guidelines for Node.js apps](https://wiki.archlinux.org/title/Node.js_package_guidelines) and how/where you're expecting users to install c-lightning-REST.

**Comment by cotsuka** [comment]
One quick final comment for those who find this in the future and are also using the Arch package (as of 0.10.5). Hacky but quick way to just get something running is to create the certs folder in the user-writable location (with my above configs it would be `/mnt/nvme/lightning/certs`) and then symlink to it:

```sh
ln -s /mnt/nvme/lightning/certs /usr/lib/node_modules/c-lightning-rest/certs
```
