### ISSUE TITLE
Error when trying to build/run c-lightning-REST API server

### ISSUE THREAD

**Issue by billygarrison** [Ride-The-Lightning/c-lightning-REST#42]
**Steps to install**
```
git clone https://github.com/Ride-The-Lightning/c-lightning-REST.git
cd c-lightning-REST
git checkout v0.3.0
npm install --only=prod
```

**Produces the following output**
```
billy@AcerUbuntu:~/builds/test/c-lightning-REST$ npm install --only=prod
npm WARN c-lightning-rest@0.3.0 No repository field.

added 146 packages from 126 contributors and audited 251 packages in 1.559s
found 0 vulnerabilities
```

**I then run `node cl-rest.js` and get**
```billy@AcerUbuntu:~/builds/test/c-lightning-REST$ node cl-rest.js
WARN: /home/billy/.lightning/lightning-rpc is missing, using the bitcoin mainnet subdirectory at /home/billy/.lightning/bitcoin instead.
/home/billy/builds/test/c-lightning-REST/node_modules/macaroon/macaroon.js:30
const utf8Encoder = new TextEncoder();
                    ^

TypeError: TextEncoder is not a constructor
    at Object.<anonymous> (/home/billy/builds/test/c-lightning-REST/node_modules/macaroon/macaroon.js:30:21)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/billy/builds/test/c-lightning-REST/utils/tasteMacaroon.js:1:80)
    at Module._compile (module.js:569:30)
```

**Comment by saubyk** [comment]
Hey @billygarrison can you please try once after running `npm install` instead. Thanks

**Comment by billygarrison** [comment]
I did try that as well.

**Comment by ShahanaFarooqui** [comment]
@billygarrison looks like your npm registry has been corrupted for some reason. Please try following steps:

1) Go to your root directory ‘c-lightning-REST’
2) Delete ‘node_modules’ folder.
3) Delete package-lock.json (Optional step).
4) Run ‘npm cache verify’.
5) Run ‘npm install --only=prod’.

**Comment by billygarrison** [comment]
I still end up with the same error after that.

**Comment by saubyk** [comment]
Hi @billygarrison assuming this is not an issue anymore, hence closing the ticket.
If it still an issue, feel free to reopen and we can troubleshoot.

Thanks

**Comment by billygarrison** [comment]
Hi @saubyk, I don't have the option to reopen the issue.

I tried again and can successfully run `npm install`, but still get the second error when running `node cl-rest.js`:

```
WARN: /home/billy/.lightning/lightning-rpc is missing, using the bitcoin mainnet subdirectory at /home/billy/.lightning/bitcoin instead.
/home/billy/builds/c-lightning-REST/node_modules/macaroon/macaroon.js:30
const utf8Encoder = new TextEncoder();
                    ^

TypeError: TextEncoder is not a constructor
    at Object.<anonymous> (/home/billy/builds/c-lightning-REST/node_modules/macaroon/macaroon.js:30:21)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/billy/builds/c-lightning-REST/utils/tasteMacaroon.js:1:80)
    at Module._compile (module.js:569:30)
```

**Comment by ShahanaFarooqui** [comment]
@billygarrison 
What are your NodeJS and npm versions?
Are you running this in an independent environment? This error is not related to the project. The “macaroon” library uses textencoder and node is unable to find it. Either it can be due to a very old version of NodeJS or it is reintegrated with other environments where NodeJS is not recognizable.

**Comment by billygarrison** [comment]
Node version was the issue, was on an old one. Thanks @ShahanaFarooqui !
