### ISSUE TITLE
Error "Cannot find module 'express'" when starting server.

### ISSUE THREAD

**Issue by RobvanB** [Ride-The-Lightning/c-lightning-REST#54]
Just installed Release v0.4.3-beta-maintenance on Linux (Ubuntu 20.04)
Followed the instructions, but when I try to start the server with "$ node cl-rest.js", I get this error:

nternal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/rob/cl-rest/c-lightning-REST-0.4.3/app.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by ShahanaFarooqui** [comment]
Were you able to successfully install all the dependencies? Above error is usually thrown when all the dependencies are not installed successfully. Can you also please share your NodeJS and npm versions

**Comment by RobvanB** [comment]
Wow you are fast :)  - I should have done a search before I posted, I had to run 'npm install express' and that fixed it.
Not sure if I missed a step from the documentation or if this needs to be added to the documentation, but after I installed it I could run the server.

**Comment by ShahanaFarooqui** [comment]
Your NodeJS and npm both are good. You might have missed ‘npm install’ step. That should also install ‘express’ for the project, no need to install it separately.
