### ISSUE TITLE
new version does not start

### ISSUE THREAD

**Issue by LightningHelper** [Ride-The-Lightning/c-lightning-REST#78]
I'm running `node cl-rest.js`
and I get this:
```
Reading config file
/hom.../c-lightning-REST-0.5.0/app.js:37
global.ln = require('./lightning-client-js')(global.config.LNRPCPATH.trim() || process.env.LN_PATH);
                                                                     ^

TypeError: Cannot read property 'trim' of undefined
    at Object.<anonymous> (/hom.../c-lightning-REST-0.5.0/app.js:37:70)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/hom.../c-lightning-REST-0.5.0/cl-rest.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

```

**Comment by saubyk** [comment]
Hi @LightningHelper 
Thanks for raising this. Missed a scenario for the new config variable. Providing a fix right away.

**Comment by saubyk** [comment]
Commit for the fix:
https://github.com/Ride-The-Lightning/c-lightning-REST/commit/6c4cf1ddb53aed2cbdae955a2992042f618354f9
